export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const UPDATE_ACTIVE_CLASS = 'UPDATE_ACTIVE_CLASS'
export const UPDATE_IS_TA = 'UPDATE_IS_TA'
